version: '3.8'
services:
  # database
  postgres:
    image: 'postgres:14-alpine'
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  # server
  server:
    stdin_open: true
    container_name: server
    build:
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./server:/srv/server
    depends_on:
      - postgres
